using AutoMapper;
using VoyageAI.API.DTOs.Activities;
using VoyageAI.API.Models.Entities;

namespace VoyageAI.API.Mapping
{
    /// <summary>
    /// AutoMapper profile for activity entity-to-DTO mappings.
    /// 
    /// This profile defines how Activity entities are mapped to/from DTOs.
    /// All mappings are configured to handle special cases and audit fields.
    /// 
    /// Mappings Defined:
    /// 1. Activity → ActivityResponse (detailed response)
    /// 2. CreateActivityRequest → Activity (on creation)
    /// 3. UpdateActivityRequest → Activity (on update)
    /// 
    /// Design Pattern: Configuration-based mapping
    /// - Loose coupling: Service doesn't know about DTO structure details
    /// - Maintainability: Changes to DTOs don't require service code changes
    /// - Testability: Mappings can be tested independently
    /// 
    /// Integration:
    /// Auto-registered in Program.cs via:
    /// services.AddAutoMapper(typeof(Program).Assembly);
    /// This discovers all Profile implementations and registers them.
    /// 
    /// General Mapping Strategy:
    /// - Property names match exactly between entity and DTOs
    /// - AutoMapper handles the mapping automatically
    /// - Custom mappings are configured in ForMember() calls for fields handled by service layer
    /// 
    /// Performance Notes:
    /// - Mappings are cached at startup for performance
    /// - No reflection overhead during request handling
    /// - Minimal memory overhead (one instance per assembly)
    /// </summary>
    public class ActivityMappingProfile : Profile
    {
        /// <summary>
        /// Initializes the activity mapping profile with all mappings.
        /// </summary>
        public ActivityMappingProfile()
        {
            // ============================================================
            // Activity → ActivityResponse (Detailed)
            // ============================================================
            // Maps entity to detailed response DTO
            // Includes all fields including audit trail
            // This is a straightforward mapping since property names match
            CreateMap<Activity, ActivityResponse>()
                .ReverseMap();

            // ============================================================
            // CreateActivityRequest → Activity
            // ============================================================
            // Maps create request to entity
            // Does NOT map these fields (service layer handles them):
            // - ActivityId: Generated by entity constructor (Guid.NewGuid())
            // - DayId: Set by service from route parameter
            // - CreatedAt: Set by service to DateTime.UtcNow
            // - UpdatedAt: Set by service to DateTime.UtcNow
            // - CreatedBy: Set by service from JWT claims
            // - LastModifiedBy: Set by service from JWT claims
            // - IsDeleted: Default to false (set by entity constructor)
            // - DeletedAt: Default to null (set by entity constructor)
            // - Status: Default to Planned (0) if not provided during creation
            // - DurationMinutes: Calculated by service from StartTime/EndTime
            CreateMap<CreateActivityRequest, Activity>()
                .ForMember(dest => dest.ActivityId, opt => opt.Ignore())
                .ForMember(dest => dest.DayId, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.LastModifiedBy, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore()) // Service sets default Planned
                .ForMember(dest => dest.DurationMinutes, opt => opt.Ignore()) // Service calculates
                .ForMember(dest => dest.ItineraryDay, opt => opt.Ignore()); // Navigation property

            // ============================================================
            // UpdateActivityRequest → Activity
            // ============================================================
            // Maps update request to entity
            // Does NOT map these fields (immutable or service-managed):
            // - ActivityId: Immutable, identifies the resource
            // - DayId: Immutable, cannot move activity to different day
            // - CreatedAt: Immutable, set at creation
            // - CreatedBy: Immutable, set at creation
            // - UpdatedAt: Set by service to DateTime.UtcNow
            // - LastModifiedBy: Set by service from JWT claims
            // - IsDeleted: Not modified by update (use DELETE endpoint instead)
            // - DeletedAt: Not modified by update (use DELETE endpoint instead)
            // - DurationMinutes: Recalculated by service if times changed
            // - Status: Can be updated only if explicitly provided (handled as nullable)
            CreateMap<UpdateActivityRequest, Activity>()
                .ForMember(dest => dest.ActivityId, opt => opt.Ignore())
                .ForMember(dest => dest.DayId, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.LastModifiedBy, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())
                .ForMember(dest => dest.DurationMinutes, opt => opt.Ignore()) // Service recalculates
                .ForMember(dest => dest.ItineraryDay, opt => opt.Ignore()); // Navigation property
        }
    }
}
