using AutoMapper;
using VoyageAI.API.DTOs.Travelers;
using VoyageAI.API.Models.Entities;

namespace VoyageAI.API.Mapping
{
    /// <summary>
    /// AutoMapper profile for Traveler entity mappings.
    /// 
    /// This profile defines how to map between Traveler entities and DTOs.
    /// AutoMapper automatically handles the conversion, reducing boilerplate code.
    /// 
    /// Mappings:
    /// 1. CreateTravelerRequest → Traveler (for creating new travelers)
    /// 2. UpdateTravelerRequest → Traveler (for updating travelers, via ForMember)
    /// 3. Traveler → TravelerResponse (for returning traveler data in responses)
    /// 
    /// Integration:
    /// Auto-registered in Program.cs via:
    /// services.AddAutoMapper(typeof(Program).Assembly);
    /// 
    /// Usage in Services:
    /// var traveler = _mapper.Map{Traveler}(createRequest);
    /// var response = _mapper.Map{TravelerResponse}(traveler);
    /// _mapper.Map(updateRequest, traveler);  // For partial updates
    /// </summary>
    public class TravelerMappingProfile : Profile
    {
        public TravelerMappingProfile()
        {
            // ========================================================
            // CreateTravelerRequest → Traveler
            // ========================================================
            CreateMap<CreateTravelerRequest, Traveler>()
                .ForMember(dest => dest.TravelerId, opt => opt.Ignore())  // ID is generated by service
                .ForMember(dest => dest.TripId, opt => opt.Ignore())  // Set by service
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())  // Set by service
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())  // Set by service
                .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())  // Set by service (UserId from JWT)
                .ForMember(dest => dest.LastModifiedBy, opt => opt.Ignore())  // Set by service
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())  // Always false for new travelers
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())  // Always null for new travelers
                .ForMember(dest => dest.Trip, opt => opt.Ignore());  // Navigation property

            // ========================================================
            // UpdateTravelerRequest → Traveler (for partial updates)
            // ========================================================
            CreateMap<UpdateTravelerRequest, Traveler>()
                .ForMember(dest => dest.TravelerId, opt => opt.Ignore())  // Never update ID
                .ForMember(dest => dest.TripId, opt => opt.Ignore())  // Never update trip association
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())  // Never update creation time
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())  // Set by service
                .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())  // Never update creator
                .ForMember(dest => dest.LastModifiedBy, opt => opt.Ignore())  // Set by service
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())  // Never update soft delete flag here
                .ForMember(dest => dest.DeletedAt, opt => opt.Ignore())  // Never update deletion time here
                .ForMember(dest => dest.Trip, opt => opt.Ignore())  // Navigation property
                .ForMember(dest => dest.Age, opt => opt.Ignore())  // Computed field
                // For partial updates, only apply non-null values
                .ForMember(dest => dest.FirstName, opt => opt.Condition(src => src.FirstName != null))
                .ForMember(dest => dest.LastName, opt => opt.Condition(src => src.LastName != null))
                .ForMember(dest => dest.MiddleName, opt => opt.Condition(src => src.MiddleName != null))
                .ForMember(dest => dest.DateOfBirth, opt => opt.Condition(src => src.DateOfBirth != null))
                .ForMember(dest => dest.Gender, opt => opt.Condition(src => src.Gender != null))
                .ForMember(dest => dest.Email, opt => opt.Condition(src => src.Email != null))
                .ForMember(dest => dest.Phone, opt => opt.Condition(src => src.Phone != null))
                .ForMember(dest => dest.Nationality, opt => opt.Condition(src => src.Nationality != null))
                .ForMember(dest => dest.PassportNumber, opt => opt.Condition(src => src.PassportNumber != null))
                .ForMember(dest => dest.PassportCountry, opt => opt.Condition(src => src.PassportCountry != null))
                .ForMember(dest => dest.PassportExpiry, opt => opt.Condition(src => src.PassportExpiry != null))
                .ForMember(dest => dest.EmergencyContactName, opt => opt.Condition(src => src.EmergencyContactName != null))
                .ForMember(dest => dest.EmergencyContactPhone, opt => opt.Condition(src => src.EmergencyContactPhone != null))
                .ForMember(dest => dest.Relationship, opt => opt.Condition(src => src.Relationship != null))
                .ForMember(dest => dest.DietaryPreference, opt => opt.Condition(src => src.DietaryPreference != null))
                .ForMember(dest => dest.SpecialRequirements, opt => opt.Condition(src => src.SpecialRequirements != null))
                .ForMember(dest => dest.FrequentFlyerNumber, opt => opt.Condition(src => src.FrequentFlyerNumber != null))
                .ForMember(dest => dest.KnownTravelerNumber, opt => opt.Condition(src => src.KnownTravelerNumber != null))
                .ForMember(dest => dest.IsPrimaryTraveler, opt => opt.Condition(src => src.IsPrimaryTraveler.HasValue));

            // ========================================================
            // Traveler → TravelerResponse
            // ========================================================
            CreateMap<Traveler, TravelerResponse>()
                .ForMember(dest => dest.Age, opt => opt.Ignore())  // Calculated property in response DTO
                .ForMember(dest => dest.DaysUntilPassportExpiry, opt => opt.Ignore())  // Calculated property
                .ForMember(dest => dest.IsPassportValid, opt => opt.Ignore());  // Calculated property
        }
    }
}
